### ISSUE TITLE
HTTP response ongeldig: bevat status regel 2 keer

### ISSUE THREAD

**Issue by ewoutp** [Nodo-Domotica/Nodo-Core#905]
In reactie op een HTTP request stuurt de Nodo 2 keer "HTTP/1.1 200 Ok" terug.
Dat is 1 keer teveel en niet conform het HTTP protocol.

Dit wordt door de meeste browsers & curl geaccepteerd, maar de Go implementatie van http accepteert het niet.

Zie https://github.com/Nodo-Domotica/Nodo-Core/blob/a50eb586d6984d9dcbb3d1b84cda9cc8ff7541d3/Nodo/Transmission.ino#L736

**Comment by Nodo-Domotica** [comment]
Terecht punt. Dank. Wordt meegenomen.
