### ISSUE TITLE
R818 - BreakOnVarEqu of BreakOnVarMore geeft foutmelding als variable gevuld is met 1

### ISSUE THREAD

**Issue by RvEldijk** [Nodo-Domotica/Nodo-Core#909]
Wellicht doe ik nog iets mis, maar onderstaande gebeurt alleen als variable 11 b.v. een 1 bevat, bij een 0 geen foutmelding en werkt het goed.

BreakOnVarEqu voorbeeld met VariableSet 11,1

BreakOnVarEqu 11,1 
Input=Serial; Unit=10; Event=BreakOnVarEqu 11,1
Input=System; Unit=10; Event=Message 1,0: Unknown command.
Output=RF; Unit=0; Event=Message 1,0: Unknown command.
Output=RF24; Unit=0; Event=Message 1,0: Unknown command.
Output=HTTP; Unit=10; Event=Message 1,0: Unknown command.

BreakOnVarEqu 11,0
Input=Serial; Unit=10; Event=BreakOnVarEqu 11,0

-------------------------------------------------------------------------------------------

BreakOnVarMore voorbeeld met VariableSet 11,1

BreakOnVarMore 11,1 
Input=Serial; Unit=10; Event=BreakOnVarMore 11,1

BreakOnVarMore 11,0
Input=Serial; Unit=10; Event=BreakOnVarMore 11,0
Input=System; Unit=10; Event=Message 1,0: Unknown command.
Output=RF; Unit=0; Event=Message 1,0: Unknown command.
Output=RF24; Unit=0; Event=Message 1,0: Unknown command.
Output=HTTP; Unit=10; Event=Message 1,0: Unknown command.

-------------------------------------------------------------------------------------------

BreakOnVarMore voorbeeld met VariableSet 11,0

BreakOnVarMore 11,1 
Input=Serial; Unit=10; Event=BreakOnVarMore 11,1
BreakOnVarMore 11,0
Input=Serial; Unit=10; Event=BreakOnVarMore 11,0

-------------------------------------------------------------------------------------------

Mijn alarm is een variable 11,..0 = aan 1 = uit, zit op een PIR op ExtWiredIn 5
Mijn eventlist;
! Alarm Huismaker
EventlistWrite; ExtWiredIn 5,Off; Sound 0,5
EventlistWrite; ExtWiredIn 5,Off; BreakOnVarEqu 11,1
EventlistWrite; ExtWiredIn 5,Off; UserEvent 75,3

Met als output;
Unit=10; Event=ExtWiredIn 5,Off
Input=Eventlist(1.76); Unit=10; Event=Sound 0,5
Input=Eventlist(1.77); Unit=10; Event=BreakOnVarEqu 11,1
Input=System; Unit=10; Event=Message 1,3: Unknown command.
Output=RF; Unit=0; Event=Message 1,3: Unknown command.
Output=RF24; Unit=0; Event=Message 1,3: Unknown command.
Output=HTTP; Unit=10; Event=Message 1,3: Unknown command.

Alarm werkt gewoon, bij 0 geen foutmelding, misschien kunnen jullie er iets mee.

Mvg

**Comment by Nodo-Domotica** [comment]
Het lijkt er ol dat de break het wel doet maar dat er onterecht een
foutmelding komt. Dit is niet de bedoeling. Ik zal hier naar kijken. Dank
voor de gedetailleerde info. Wordt vervolgd.

Groeten Paul.

Op vr 29 mei 2015 08:31 schreef RvEldijk <notifications@github.com>:

**Comment by RvEldijk** [comment]
Graag gedaan, en dank je wel !!

Mvg Rene

**Comment by Nodo-Domotica** [comment]
Opgelost in komende build. Nu komt er een break bericht.
