### ISSUE TITLE
R818 - PLUGIN_006 DHT-22 geeft geen waardes door aan webapp

### ISSUE THREAD

**Issue by RvEldijk** [Nodo-Domotica/Nodo-Core#910]
Wellicht doe ik iets verkeerd waardoor waardes niet doorgegeven worden aan de webapp, 
ik probeer de waardes van de DHT-22 op poort D30 (mega) of D7 (shield) in de webapp te krijgen.

Commando ;
DHTRead 1,1

Output ;
DHTRead 1,1
Input=Serial; Unit=10; Event=DHTRead 1,1
Trace-1
Trace-2
Trace-4
Trace-5

Status all;
VariablePayload 1,0x11
VariablePayload 2,0xD1
VariablePayload 3,0xD1
VariablePayload 4,0x11
VariablePayload 5,0x11
VariablePayload 6,0x11
VariablePayload 7,0x11
VariableSet 1,0
VariableSet 2,0

Config_01.c
#define PLUGIN_006_CORE DHT-22 // Vochtigheid-/temperatuursensor DHT-22

Plugin_006.c
#define PLUGIN_ID 6
#define PLUGIN_NAME "DHTRead"
#define DHT_EVENT true  // false=geen events genereren bij uitlezen, true genereert wel events.

Als ik ergens mee kan helpen hoor ik dat graag !!

Mvg

**Comment by Nodo-Domotica** [comment]
Ik zal de plugin asap testen, maar ik zie een regel niet goed staan :

Config_01.c
#define PLUGIN_006_CORE DHT-22

Moet zijn:

Config_01.c
#define PLUGIN_006_CORE 22

Op vr 29 mei 2015 09:46 schreef RvEldijk <notifications@github.com>:

Wellicht doe ik iets verkeerd waardoor waardes niet doorgegeven worden aan

**Comment by RvEldijk** [comment]
Dat zal hoogstwaarschijnlijk het probleem dan geweest zijn, ik heb maar 1 DHT-22, zodra ik het systeem weer overzet naar de nieuwe versie kan ik dit even testen, wss moet de wiki en plugin info ook dan nog aangepast worden.

**Comment by RvEldijk** [comment]
Het werkt inderdaad met;

Config_01.c 
#define PLUGIN_006_CORE 22

Dank !
