### ISSUE TITLE
R818 Plugin 21 compile error

### ISSUE THREAD

**Issue by koningdde** [Nodo-Domotica/Nodo-Core#912]
Bij plugin 21 wordt gebruik gemaakt van EthernetNodo, dit klopt niet meer, Ethernet.h wordt gebruikt in plaats van Ethernetnodo.h

op 5 plaatsen in de plugin moet Ethernetnodo.h veranderd worden in Ethernet.h

**Comment by Nodo-Domotica** [comment]
Correct. Deze plugjn moet nog worden aangepast. Thanks.

Op ma 1 jun. 2015 11:21 schreef koningdde <notifications@github.com>:

**Comment by laikaatje** [comment]
Klopt.Doch ik maar vier maal EthernetNodo gevonden.Deze vier veranderd en komt nu goed door compiler 1.0.6  Nodo LCD 4 regels. Core4 ingevuld,maar nog steeds problemen.Nog geen NRF module en hangt niet aan ethernet. Wanneer serieel input via usb : LCDWrite 3,1,Clock. Dan reply :Input=System:Unit=1;Event=Message 14,21;Plugin returned an error .Wanner via serieel Status Nodo opvraag geeft plugin 021.c goed.Snap het niet meer Help.

**Comment by Nodo-Domotica** [comment]
Hoi

Het is voor het Nodoteam zomerreces.  Zodra de vakantieperiode weer voorbij
is starten we weer met ontwikkelen en issues oplossen.

Groeten Paul.

Op zo 19 jul. 2015 15:04 schreef laikaatje <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Plugin aangepast: vier maal verwijzing naar de juiste library. @laikaatje: Als er nog andere problemen zijn, zou je hiervoor dan een separaat issue willen aanmaken?

Groeten Paul.

**Comment by laikaatje** [comment]
Goedendag Paul,

Nieuwe versie geladen doch nog steeds compiler problemen.Ik wil wel de juiste problemen doorgeven maar snap niet precies wat je bedoeld met separaat issue aanmaken.
Kan ik niet gewoon communiceren via nodo forum en dan tot wie moet ik mij dan  richten?Van github niet zoveel kaas gegeten. 
In afwachting verblijf ik,
Hans

**Comment by Nodo-Domotica** [comment]
Mail in dit geval het probleem maar even direct via p.k.tonkes@gmail.com

Groeten

Op vr 28 aug. 2015 11:29 schreef laikaatje <notifications@github.com>:
