### ISSUE TITLE
R818 compile error for OSX users

### ISSUE THREAD

**Issue by koningdde** [Nodo-Domotica/Nodo-Core#913]
Ik gebruik een arduino compiler op een MAC, de SKETCH_PATH ziet er zo uit:
#define SKETCH_PATH /Users/danny/Documents/Arduino/nodo881/Nodo

tijdens de compilatie kan hij de mappen hardware en config niet vinden om deze reden:
#define CONFIGFILE2(a, b) stringify(a/Config/b)
#define HARDWAREFILE2(a, b) stringify(a/Hardware/HW-b.h)
Ik heb de \ veranderd in /, dan werkt het wel.

**Comment by Nodo-Domotica** [comment]
Ah, de bekende strijd tussen Windows en UX. Zal er naar kijken. ;-)

Op ma 1 jun. 2015 11:22 schreef koningdde <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Aangepast. komt mee met de volgende build. Thanks.
