### ISSUE TITLE
R818 compile error for plugin.ino

### ISSUE THREAD

**Issue by koningdde** [Nodo-Domotica/Nodo-Core#914]
Deze tekst is niet juist, staat in diverse plugins:
// LET OP: Deze plugin moet nog worden aangepast voor het gebruik van globale variabelen en variabelenummers
// hoger dan 15. Zolang deze plugin nog niet is aangepast moeten de onderstaande reges in het confif.xx.c bestand 
// worden opgenomen
#define PLUGIN_37_COMPATIBILITY

Wat wel aangepast moet worden is dit:
En deze regel aangepast in plugin.no:
#if PLUGIN_37_COMPATIBILITY

#if defined(PLUGIN_37_COMPATIBILITY)

En dan in plugin.ino deze regel aanpassen om het werkent te krijgen:
#define PLUGIN_37_COMPATIBILITY false >> #define PLUGIN_37_COMPATIBILITY true

**Comment by Nodo-Domotica** [comment]
Thanks.

Op ma 1 jun. 2015 11:26 schreef koningdde <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Eigenlijk is de compatibility niet wenselijk en moeten de plugins worden aangepast. Dus wellicht is info weghalen en de stofkam door de plugins beter. Ik sluit dit issue en zal binnen het team bespreken hoe we komen tot verversing van de plugins.

**Comment by Nodo-Domotica** [comment]
sluiten.
