### ISSUE TITLE
VariableInc in een bestand geeft verkeerde waarde, aangeroepen door FileExecute

### ISSUE THREAD

**Issue by RvEldijk** [Nodo-Domotica/Nodo-Core#919]
VariableInc 12,1 in een bestand dat door FileExecute vanuit de eventlist word aangeroepen resulteerd in een foute waarde, ik heb b.v. in mijn eventlist staan;

EventlistWrite; Timer 1; FileExecute 22

Als dan in bestand 22, een VariableInc 12,1 actie gedaan moet worden, pakte hij b.v. variable 1 als waarde, wat b.v. de temperatuur is, wat dan in Variable 12,24.813 resulteerde.

**Comment by Nodo-Domotica** [comment]
Da's niet d er bedoeling.  Kijken we naar na de zomerreces.

Op ma 3 aug. 2015 13:47 schreef RvEldijk <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Ik kan het niet reproduceren, maar ik vermoed dat het onjuist zetten van de variabele wordt veroorzaakt door een plugin. Welke plugin(s) gebruik je die de waarde 24.813 heeft opgeleverd?

!******************************************************************************!
Nodo Domotica controller V3.8 BETA (Mega)
(c) Copyright 2015 P.K.Tonkes. Licensed under GNU General Public License.
Product=SWACNC-MEGA-R817, ThisUnit=10
Date=25-08-2015 (Tue); Time=22:15 DaylightSaving
!******************************************************************************!

Input=System; Unit=10; Event=Boot 10
Output=IR; Unit=0; Event=Boot 10
Output=RF; Unit=0; Event=Boot 10
Output=RF24; Unit=0; Event=Boot 10
Output=I2C; Unit=0; Event=Boot 10
Input=System; Unit=10; Event=Message 19,0: Hardware configuration error(s).
Output=RF; Unit=0; Event=Message 19,0: Hardware configuration error(s).

Ready. Nodo is waiting for serial input...

>eventlistshow
Input=Serial; Unit=10; Event=EventlistShow 0
!******************************************************************************!
1: Timer 1; FileExecute 22,Off
2: Timer 1; TimerSet 1,5
!******************************************************************************!
>
>fileshow 22
!******************************************************************************!
VariableInc 12,1
!******************************************************************************!
>
>timer 1
Input=Serial; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,1
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
>Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,2
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,3
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,4
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,5
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,6
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,7
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,8
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,9
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,10
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,11
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,12
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,13
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,14
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,15
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,16
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,17
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,18
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,19
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,20
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,21
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,22
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,23
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,24
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,25
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,26
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,27
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,28
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,29
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,30
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,31
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,32
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,33
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,34
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,35
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,36
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,37
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,38
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,39
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,40
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,41
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,42
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,43
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,44
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,45
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,46
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,47
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,48
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,49
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,50
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5
Input=Clock; Unit=10; Event=Timer 1
Input=Eventlist(1.1); Unit=10; Event=FileExecute 22,Off
VariableInc 12,1
Input=File; Unit=10; Event=VariableInc 12,1
Input=System; Unit=10; Event=Variable 12,51
Input=Eventlist(1.2); Unit=10; Event=TimerSet 1,5

**Comment by RvEldijk** [comment]
Ik denk dan de Dallas, die had net als laatste meting 22.68, via de webapp met het commando "VariableInc 20,1" en kreeg ik "23.68" i.p.v. "1", lijkt erop dat hij die gegevens kreeg "Variable 7".

Klopt het dat alle variables weg zijn bij het herstarten, totdat ze gevuld worden, probeer het probleem nu nogmaals te reproduceren, echter zonder suc6.

Input=System; Unit=10; Event=Variable 7,22.688; Payload=0x11
Input=System; Unit=10; Event=Variable 20,23.688

Var 1-2 DHT 22
Var 3-7 Dallas

----------------
Plugin 1
Plugin 2
Plugin 5
Plugin 6
Plugin 25
Plugin 26
Plugin 27
Plugin 29
Plugin 30
----------------
TimerSet 1,348
VariablePayload 1,0x11
VariablePayload 2,0xD1
VariablePayload 3,0x11
VariablePayload 4,0x11
VariablePayload 5,0x11
VariablePayload 6,0x11
VariablePayload 7,0x11
VariableSet 1,21.100
VariableSet 2,63.100
VariableSet 3,23.438
VariableSet 4,18.438
VariableSet 5,22.813
VariableSet 6,22.938
VariableSet 7,22.668
VariableSet 8,1
VariableSet 9,0
VariableSet 10,1
VariableSet 11,1
VariableSet 12,1
VariableSet 13,0
VariableSet 20,23.688
WiredAnalog 1,976
------------------

**Comment by Nodo-Domotica** [comment]
Klopt. Variabelen worden pas getoond na gebruik. Je heb variabelenummers
1..255 tot je beschikking. Ik zal de plugin eens tegen het licht houden.

Op vr 28 aug. 2015 23:48 schreef RvEldijk <notifications@github.com>:

**Comment by RvEldijk** [comment]
Wat me verder ook opviel, als de variabelen niet "gevuld" zijn door een opstart of reboot, als je dan in je eventlist hebt staan "BreakOnVarNEqu 13,1" dan gaat hij er gewoon doorheen, en voert hij uit wat niet de bedoeling is. Ik heb dit nu opgelost door een VariableSave 13 mee te geven zodat hij bij de boot wel bestaat.

**Comment by Nodo-Domotica** [comment]
Die is interessant. Daar zal ik een aanpassing voor maken!

Op di 1 sep. 2015 23:56 schreef RvEldijk <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
opgelost in volgende build
