### ISSUE TITLE
Led blijft blauw

### ISSUE THREAD

**Issue by gmos** [Nodo-Domotica/Nodo-Core#920]
In Transmission.ino gaat op regel 25 in SendEvent de led op blauw voor een broadcast.
Maar het na de broadcast terugzetten gebeurt nergens.
Voorlopig opgelost met:
#if HARDWARE_STATUS_LED_RGB
  if(Broadcast)
    Led(GREEN);
#endif
aan het eind van de routine. Lijkt goed te werken.

**Comment by Nodo-Domotica** [comment]
Thanks zal er naar kijken na de zomerreces.

Op za 8 aug. 2015 14:52 schreef Gijs Mos <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Eigenlijk hoort de aansturing van de blauwe led hier niet thuis. Deze kleur is bedoeld als de Nodo 'onder water'  is, maar niet bezig met verwerken van events. Denk hierbij aan initialiseren, resetten, etc.
