### ISSUE TITLE
R818 - NRF24L01+PA+LNA SMA

### ISSUE THREAD

**Issue by RvEldijk** [Nodo-Domotica/Nodo-Core#921]
Als ik de standaard NRF module verbind met de daarvoor geschikte adapter gaat het goed, echter bij de versie met losse antenne (NRF24L01+PA+LNA SMA), boot de nodo wel maar blijft hangen bij; (reageert verder ook nergens meer op IR, Webapp, 433, etc)

(NRF24L01+PA+LNA)
Output=IR; Unit=0; Event=Boot 10
Output=RF; Unit=0; Event=Boot 10
Output=RF24; Unit=0; Event=Boot 10

(Standaard NRF module)
Output=IR; Unit=0; Event=Boot 10
Output=RF; Unit=0; Event=Boot 10
Output=RF24; Unit=0; Event=Boot 10
Output=I2C; Unit=0; Event=Boot 10
Output=HTTP; Unit=10; Event=Boot 10
Ready. Nodo is waiting for serial input...

Zie wel tijdens het booten in beide gevallen RF 2.4Ghz: Ok.

Wissel hem alleen om in de adapter, in alle gevallen een 5v/10a voeding (5.12v), 2 ruimtes verderop hangt een R818 mini met NRF24L01+PA+LNA en die doet het wel goed. Kan me nog herinneren bij de vorige versie dat hij niet eens wilde booten met de losse antenne op de centrale nodo.

Nodo Domotica controller V3.8 BETA (Mega)
(c) Copyright 2015 P.K.Tonkes. Licensed under GNU General Public License.
Product=SWACNC-MEGA-R817, ThisUnit=10, ID=A5SLACTT
Date=29-08-2015 (Sat); Time=19:59 DaylightSaving
IP=192.168.50.198, PortOutput=80, PortInput=6636

!******************************************************************************!

HWConfig 0x400BE717
HWStatus 0x400BE717

**Comment by RvEldijk** [comment]
Ook even van de 9v voeding (die naar de arduino gaat), volt converter naar 5v ertussen, echter zonder succes

**Comment by Nodo-Domotica** [comment]
Ik vermoed toch dat het hardware betreft. Beide modellen werken bij mij. De
sma/pa versie trekt een hoge stroom. Het boot event verzenden is het eerste
moment waarop de zender daadwerkelijk vermogen vraagt. Waarschijnlijk
ontstaan er spanningsdippen op de voedingslijn die de ATMega laat stoppen
(spanning onder de brown-out). Zet eens een flinke tantaal condensator
(25uF) dicht bij de NRF en zorg voor solide massa zonder aardlussen. Ik heb
zonder problemen met de NRF afstand van 500m binnen bebouwing gehaald.

Laat even weten.

Op za 29 aug. 2015 00:54 schreef RvEldijk <notifications@github.com>:

**Comment by RvEldijk** [comment]
Ongelooflijk "its working" nou met een 100 en 10UF condensator erop, bovenop de orignele NRF 5v adapter, en nou loopt hij goed. Wist dat ze standaard op de NRF modules moesten, maar dat het niet meer hoefde met die orginele NRF 5v adapters, maar blijkbaar dus ook nog, met de standaard nrf modules kwam ik al twee ruimtes verderop niet meer, wel erg dikke muren.

Duizend maal dank !!!

**Comment by Nodo-Domotica** [comment]
;-)

Op di 1 sep. 2015 23:51 schreef RvEldijk <notifications@github.com>:
