### ISSUE TITLE
Hallo Paul

### ISSUE THREAD

**Issue by laikaatje** [Nodo-Domotica/Nodo-Core#922]
Nieuwe R817 gedownload.Na aanpassingen plugin 021(prog_char naar const char en *LCDtextlabel naar *const LCDtext_label) Tevens diverse hardware uitgezet in config_01.c Daarna geupload naar admega. Bij compiler V1.6.1 hangt serieel com.Bij compiler V1.0.6 schijnt alles te werken,doch wel problemen met LCD scherm.LCDwrite 3,1,IP dan op scherm 255.255.255.255(hangt nog niet aan het net).LCDWrite 3,1,Clock dan wordt regel overschreven met alles blanco.Bij versie R744 werkt wel alles op scherm.Het lijkt er op dat data van clock niet opgehaald wordt.Help !!
ÿÿÿÿÿSerial-1 port: Ok.
Nodo Mega: Ok.
RF 433Mhz: Ok.
WiredIn port: Ok.
WiredOut port: Ok.
SDCard: Ok.
I2C: Ok.
Realtime clock: Ok.
Software SPI: Ok.

!******************************************************************************!
Nodo Domotica controller V3.8 BETA (Mega)
(c) Copyright 2015 P.K.Tonkes. Licensed under GNU General Public License.
Product=SWACNC-MEGA-R817, ThisUnit=1
Date=30-08-2015 (Sun); Time=12:13 DaylightSaving
!******************************************************************************!
Input=System; Unit=1; Event=Boot 1
Output=RF; Unit=0; Event=Boot 1
Output=I2C; Unit=0; Event=Boot 1

Ready. Nodo is waiting for serial input...

lcdwrite 3,1,ip
Input=Serial; Unit=1; Event=LCDWrite 3,1,IP,0
>lcdwrite 4,1,clock
Input=Serial; Unit=1; Event=LCDWrite 4,1,Clock,0
>lcdwrite 3,1,clock
Input=Serial; Unit=1; Event=LCDWrite 3,1,Clock,0
>

**Comment by Nodo-Domotica** [comment]
Hoi. Ik zal dit issue bekijken. Omdat ik niet het betreffende lcd scherm bezit zal ik vermoedelijk je hulp kunnen gebruiken. 

Wordt vervolgd

**Comment by DiscusPeter** [comment]
Heren, het probleem dat de clock niet wordt gediplayed zit hem in het feit dat er in de plugin nog gebruik wordt gemaakt van #if CLOCK en dit moet sinds versie 3.8 zijn #if HARDWARE_CLOCK

**Comment by Nodo-Domotica** [comment]
Dat scheelt mij weer zoeken, dank. Update staat klaar in GitHub.

Op vr 4 sep. 2015 21:42 schreef DiscusPeter <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Opgelost. Dank aan Peter.
