### ISSUE TITLE
Foutje in plugin_021

### ISSUE THREAD

**Issue by laikaatje** [Nodo-Domotica/Nodo-Core#925]
Hallo Paul en andere Nodo gebruikers. Ik heb de #if CLOCK veranderd in #if HARDWARE_CLOCK en het werkt nu. Maar het vreemde is dat het alleen werkt met IDE 1.0.6. Met IDE 1.6.1 en IDE 1.6.4 loopt de zaak vast. Uploaden lukt dan wel, maar in serieel opdracht b.v. LCDWrite 4,1,IP loopt de boel vast. Met uploaden met IDE 1.6.1 en vervolgens verder  met IDE 1.0.6. opdracht LCDWrite 3,1,CLOCK werkt het perfect. Hier geen oplossing voor. Het werkt wel verwarrend aangezien in de aanhef in nodo.ino gesproken wordt over compiler V1.6.1

**Comment by DiscusPeter** [comment]
Hi laikaatje. Ik liep tegen hetzelfde probleem aan. Deze plugin is blijkbaar nog niet omgebouwd voor de nieuwe compiler.
Na wat zoeken blijkt dat je een aantal regels moet vervangen. Dit is de nieuwe code volgens mij:
PROGMEM const char LCD_01[] = PLUGIN_021_LABEL_01;
PROGMEM const char LCD_02[] = PLUGIN_021_LABEL_02;
PROGMEM const char LCD_03[] = PLUGIN_021_LABEL_03;
PROGMEM const char LCD_04[] = PLUGIN_021_LABEL_04;
PROGMEM const char LCD_05[] = PLUGIN_021_LABEL_05;
PROGMEM const char LCD_06[] = PLUGIN_021_LABEL_06;
PROGMEM const char LCD_07[] = PLUGIN_021_LABEL_07;
PROGMEM const char LCD_08[] = PLUGIN_021_LABEL_08;
PROGMEM const char LCD_09[] = PLUGIN_021_LABEL_09;
PROGMEM const char LCD_10[] = PLUGIN_021_LABEL_10;
PROGMEM const char LCD_11[] = PLUGIN_021_LABEL_11;
PROGMEM const char LCD_12[] = PLUGIN_021_LABEL_12;
PROGMEM const char LCD_13[] = PLUGIN_021_LABEL_13;
PROGMEM const char LCD_14[] = PLUGIN_021_LABEL_14;
PROGMEM const char LCD_15[] = PLUGIN_021_LABEL_15;
PROGMEM const char LCD_16[] = PLUGIN_021_LABEL_16;
PROGMEM const char LCD_17[] = PLUGIN_021_LABEL_17;
PROGMEM const char LCD_18[] = PLUGIN_021_LABEL_18;
PROGMEM const char LCD_19[] = PLUGIN_021_LABEL_19;
PROGMEM const char LCD_20[] = PLUGIN_021_LABEL_20;

#define LCDI2C_MSG_MAX        20

const char* const LCDText_tabel[] PROGMEM={LCD_01,LCD_02,LCD_03,LCD_04,LCD_05,LCD_06,LCD_07,LCD_08,LCD_09,LCD_10,LCD_11,LCD_12,LCD_13,LCD_14,LCD_15,LCD_16,LCD_17,LCD_18,LCD_19,LCD_20};

Wel blijkt er nog een andere fout in te zitten. Als je een variabele op het display wilt zetten dan kan je geen hogere variabele opgeven dan 16. Met ingang van Nodo 3.8 zijn ook hogere nummers mogelijk maar de max waarde van 16 zit nu hard gecodeerd. Beter is het volgens mij om deze te vervangen door USER_VARIABLES_MAX_NR.
Hopelijk kan Paul e.e.a. eens bekijken en officieel maken.

**Comment by laikaatje** [comment]
Hi DiskusPeter. Heb jou suggestie geprobeerd maar het probleem blijft hetzelfde met dit verschil dat de mega nu vastloopt met IDE 1.0.6 als ook met IDE 1.6.1. Nog iets vreemds ontdekt. Bij opstarten mega wordt soms de of de eerste en/of de tweede regel op lcd niet volledig compleet gevuld met  karakters.
Nodo domotica. Mega R:820 U:1. Tussen haakjes: plugin aangepast zoals behandeld in gesloten issue #915. Help, het wordt voor mij steeds onduidelijker.

**Comment by Nodo-Domotica** [comment]
Ik zal naar de plugin kijken. @laikaatje:probeer eens als de Mega vastloopt
de I2C verbinding los te maken. De originele I2C library heeft geen timeout
beveiliging wanneer de I2C communicatie onbedoeld niet volgens protocol
verloopt. Normaal gesproken hoeft dat geen probleem te zijn, maar wel als
de I2C verbinding niet stabiel is. Wat vaak wordt vergeten is dat de I2C
lijnen SDA en SLC beide via een pull-up weerstand van 4k7 met de 5V
verbonden moeten worden. Kun je dat testen? Ik zal kijken of ik ergens een
LCD schermpje heb liggen om ook e.e.a. te testen.

Op 9 september 2015 09:53 schreef laikaatje <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Ik had nog een LCD display liggen. De plugin is aangepast. Hij komt nu door
de compiler V1.6.1. Ook worden variabelen boven 15 getoond. Plugin loopt
hier zonder hangers.

Op 9 september 2015 21:12 schreef Paul Tonkes <p.k.tonkes@gmail.com>:

**Comment by Nodo-Domotica** [comment]
Tevens toegevoegd dat de gebruikersvariabele 'temp' kan worden geprint. deze variabele mag een string bevatten en kan worden gebruikt in bv. een scriptfile.

**Comment by laikaatje** [comment]
Nieuwe core-master gedownload. Komt nu door compiler 1.6.1. Krijg hem ook geüpload. Wat betreft de weerstanden, dit maakt geen verschil. Er blijven random karakters van de eerste twee regels wegvallen na opstarten. Ik had ook verondersteld dat SLC enSDA in IC hoogohmig waren afgesloten net als de inputs en outputs   Maar nu is er weer een nieuw probleem bij gekomen. Kan geen serieel commando meer versturen naar de mega. De mega zelf hangt niet want het scherm wordt elke minuut ververst i.v.m. de klok.

**Comment by Nodo-Domotica** [comment]
De SDA en SCL zijn juist niet hoogohmig, maar moeten pullup weerstanden
hebben. Ik zou je problemen zoeken in de voeding en bedrading. Hier draait
het probleemloos.

Op do 10 sep. 2015 22:31 schreef laikaatje <notifications@github.com>:

**Comment by Nodo-Domotica** [comment]
Ik heb de plugin met het LCD scherm nu vier dagen onafgebroken werken zonder een hik. Ik sluit dit issue. Mocht je nog hardware problemen hebben, doe dan even een post op het forum. Ok?

Groeten Paul.
